# This file is a template, and might need editing before it works on your project.
# This file is a template demonstrating the `script` keyword.
# Learn more about this keyword here: https://docs.gitlab.com/ee/ci/yaml/README.html#script

# After committing this template, visit CI/CD > Jobs to see the script output.
image: node:latest

stages: 
  - build
  - notify

build-install:
  stage: install
  script:
    # provide a shell script as argument for this keyword.
    - npm install
    - npm run build

notify:
  stage: notify
  script: 
    - echo "build done"
